import Game.Metadata
import Mathlib.GroupTheory.PGroup

World "GroupAction"

Level 7

Title "Cauchy's Theorem"

Introduction "
Cauchy's theorem states: if a prime p divides the order of a finite group G,
then G contains an element of order p.

The elegant proof (due to James McKay, 1959) uses group actions.
Consider the set of p-tuples (g₁, g₂, ..., gₚ) ∈ Gᵖ with g₁ · g₂ · ... · gₚ = 1.
The cyclic group ℤ/pℤ acts on this set by cyclic rotation. By the fixed-point
counting lemma, the number of fixed points is congruent to the size of the set mod p.

A fixed point is a constant tuple (g, g, ..., g) with gᵖ = 1, i.e., an element of order
dividing p. Since (1, 1, ..., 1) is always a fixed point and p divides the total count,
there must be another fixed point, giving a non-identity element g with gᵖ = 1.
Since p is prime, g has order exactly p.

In Lean, this is `exists_prime_orderOf_dvd_card`.
"

variable {G : Type*} [Group G] [Fintype G]

Statement {p : ℕ} [Fact (Nat.Prime p)] (hdvd : p ∣ Fintype.card G) :
    ∃ g : G, orderOf g = p := by
  Hint "Apply `exists_prime_orderOf_dvd_card` with the prime p and the divisibility hypothesis."
  exact exists_prime_orderOf_dvd_card p hdvd

Conclusion "
Cauchy's theorem is the first step toward the Sylow theorems.
It guarantees that if a prime p divides |G|, then G has a subgroup of order p
(the cyclic group generated by the element of order p).

The Sylow theorems go much further: if pⁿ is the largest power of p dividing |G|,
then G has a subgroup of order pⁿ (a Sylow p-subgroup), and all such subgroups
are conjugate.
"

NewTheorem exists_prime_orderOf_dvd_card orderOf Fintype.card
