import Game.Levels.GroupBasics.L01_mul_assoc
import Game.Levels.GroupBasics.L02_assoc
import Game.Levels.GroupBasics.L03_inverse_def
import Game.Levels.GroupBasics.L04_inverse
import Game.Levels.GroupBasics.L05_inverse_unique
import Game.Levels.GroupBasics.L06_Subgroup_def
import Game.Levels.GroupBasics.L07_kZ
import Game.Levels.GroupBasics.L08_Zn
import Game.Levels.GroupBasics.L09_Commutator
import Game.Levels.GroupBasics.L10_ElementaryTwoGroup
