import Game.Metadata

World "BasicGroupTheory"

Level 16

Introduction "
The **Klein four-group** is V = C₂ x C₂, the direct product of two copies of the cyclic group of order 2. It has order 4, and every non-identity element has order 2.

A group is **cyclic** if it is generated by a single element g, meaning every element equals g^n for some integer n. A cyclic group of order n has an element of order n.

We prove here that V = C₂ x C₂ is **not** cyclic. The key idea: if V were cyclic of order 4, it would have an element of order 4. But every element of V satisfies x^2 = 1, so every element has order at most 2 -- a contradiction.
"

open Monoid Group
open scoped Pointwise



theorem C2_prod_C2_not_cyclic {C : Type u_1} [Group C] [Fintype C]  (h : Nat.card C = 2) : ¬ IsCyclic (C × C) := by
  intro H
  Hint "First compute |C x C| = 4. The theorem `Nat.card_prod` gives |C x C| = |C| * |C|, and we know |C| = 2 from `{h}`."
  have order4 : Nat.card (C × C) = 4 := by simp only [Nat.card_prod,h]
  Hint "If a group is cyclic, there exists an element whose order equals the cardinality of the group. This is `IsCyclic.exists_ofOrder_eq_natCard`. Extract this witness:
  `replace h1 := IsCyclic.exists_ofOrder_eq_natCard (h := H)`
  "
  replace h1 := IsCyclic.exists_ofOrder_eq_natCard (h:=H)
  Hint "Now rewrite `{h1}` using `{order4}` so that Nat.card (C x C) becomes 4. Use `rw [{order4}] at {h1}`."
  rw [order4] at h1
  Hint "Next we show every element of C satisfies c^2 = 1. The theorem `pow_card_eq_one'` says g^(Nat.card G) = 1 for any element g. Since |C| = 2, we get c^2 = 1. Establish this with:
  `have square_one (c : C) : c ^ 2 = 1 := by simp [<-h]`
  "
  have square_one (c : C) : c ^ 2 = 1 := by rw [← h]; exact pow_card_eq_one'
  Hint "Now lift this to C x C: for any (a, b) in C x C, (a, b)^2 = (a^2, b^2) = (1, 1). In Lean, equality of pairs reduces to componentwise equality via `ext`. Then `simp [square_one]` finishes each component.
  "
  replace square_one (c : C × C) : c ^ 2 = 1 := by
    ext<;>simp only [Prod.pow_fst, Prod.pow_snd, square_one, Prod.fst_one, Prod.snd_one]
  Hint "The theorem `orderOf_le_of_pow_eq_one` says: if n > 0 and g^n = 1, then orderOf g <= n. Apply this to show every element of C x C has order at most 2."
  have orderle2 : ∀ g : C × C, orderOf g ≤ 2 := by
    intro g
    apply orderOf_le_of_pow_eq_one
    Hint "The first subgoal asks to show 0 < 2. Use `linarith` to close numeric inequalities automatically."
    linarith
    Hint "Now show g^2 = 1 using `simp [{square_one}]`."
    exact square_one g
  Hint "We now have a contradiction: `{h1}` says some element has order 4, but `{orderle2}` says every element has order at most 2. Use `obtain` to extract the element g from `{h1}`."
  obtain ⟨g, hg⟩ := h1
  Hint "Apply `{orderle2}` to the specific element g using `specialize {orderle2} g`. This gives orderOf g <= 2."
  specialize orderle2 g
  Hint "Now `{hg}` says orderOf g = 4 and `{orderle2}` says orderOf g <= 2. These are contradictory. The `linarith` tactic closes goals that follow from linear arithmetic over the hypotheses."
  linarith
